// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Utils$RescriptPpx from "../utils/Utils.bs.js";
import * as Tailwind$RescriptPpx from "../styles/tailwind/Tailwind.bs.js";

var background = Tailwind$RescriptPpx.twStyle([Tailwind$RescriptPpx.bg(undefined, "blue500")]);

var header = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.mx("v80"),
      Tailwind$RescriptPpx.p("v6"),
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textColor(undefined, "white")
    ]);

var navbar = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mb("v24")
    ]);

var logo = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.text("xl4"),
      Tailwind$RescriptPpx.itemsCenter
    ]);

var navUl = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var anchor = Tailwind$RescriptPpx.twStyle([Tailwind$RescriptPpx.mx("v4")]);

var featuresSection = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.mx("v80"),
      Tailwind$RescriptPpx.pb("v12")
    ]);

var featuresFlex = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textColor(undefined, "white"),
      Tailwind$RescriptPpx.justifyBetween
    ]);

var featuresImage = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.h("v48"),
      Tailwind$RescriptPpx.w("v48")
    ]);

var featuresHeading = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.text("xl6"),
      Tailwind$RescriptPpx.mb("v6")
    ]);

var featuresParagraph = Tailwind$RescriptPpx.twStyle([Tailwind$RescriptPpx.text("lg")]);

var docsSection = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.bg(undefined, "white"),
      Tailwind$RescriptPpx.pt("v12"),
      Tailwind$RescriptPpx.pb("v2")
    ]);

var docsFlex = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mx("v60"),
      Tailwind$RescriptPpx.mb("v12")
    ]);

var essentialsBackground = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.bg(undefined, "gray100"),
      Tailwind$RescriptPpx.p("v8"),
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.w("v76"),
      Tailwind$RescriptPpx.rounded("xl2"),
      Tailwind$RescriptPpx.shadow("xl2"),
      Tailwind$RescriptPpx.mb("v92")
    ]);

var docsHeading = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.text("lg"),
      Tailwind$RescriptPpx.my("v4")
    ]);

var docsParagraph = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.borderB("v2"),
      Tailwind$RescriptPpx.mb("v4")
    ]);

var essentialsBackground2 = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.bg(undefined, "white"),
      Tailwind$RescriptPpx.p("v8"),
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.rounded("xl2"),
      Tailwind$RescriptPpx.shadow("xl2")
    ]);

var infoPop = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyCenter,
      Tailwind$RescriptPpx.bg(undefined, "green500"),
      Tailwind$RescriptPpx.p("v2"),
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.rounded("lg"),
      Tailwind$RescriptPpx.mt("v6")
    ]);

var infoIcon = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.w("v8"),
      Tailwind$RescriptPpx.h("v8")
    ]);

var popParagraph = Tailwind$RescriptPpx.twStyle([Tailwind$RescriptPpx.pl("v4")]);

var introductionHeading = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.text("xl2"),
      Tailwind$RescriptPpx.mb("v2")
    ]);

var introductionHeading2 = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.text("lg"),
      Tailwind$RescriptPpx.my("v4")
    ]);

var cliInstall = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.bg(undefined, "blue500"),
      Tailwind$RescriptPpx.my("v4"),
      Tailwind$RescriptPpx.p("v2"),
      Tailwind$RescriptPpx.w("v36"),
      Tailwind$RescriptPpx.rounded("lg"),
      Tailwind$RescriptPpx.textColor(undefined, "white")
    ]);

var codePre = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.bg(undefined, "gray800"),
      Tailwind$RescriptPpx.textColor(undefined, "white"),
      Tailwind$RescriptPpx.p("v2"),
      Tailwind$RescriptPpx.my("v2"),
      Tailwind$RescriptPpx.rounded("lg")
    ]);

var footerSection = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.bg(undefined, "indigo900"),
      Tailwind$RescriptPpx.textColor(undefined, "white")
    ]);

var footerFlex = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mx("v56"),
      Tailwind$RescriptPpx.py("v18")
    ]);

var footerLeft = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.block,
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var footerHeading = Tailwind$RescriptPpx.twStyle([Tailwind$RescriptPpx.text("xl3")]);

var footerRight = Tailwind$RescriptPpx.twStyle([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.h("v14"),
      Tailwind$RescriptPpx.w("v14"),
      Tailwind$RescriptPpx.mr("v28")
    ]);

var footerImage = Tailwind$RescriptPpx.twStyle([Tailwind$RescriptPpx.mx("v4")]);

function $$default(param) {
  return React.createElement("main", {
              className: background
            }, React.createElement("header", {
                  className: header
                }, React.createElement("nav", {
                      className: navbar
                    }, React.createElement("div", undefined, React.createElement("a", {
                              href: "loruki"
                            }, React.createElement("h1", {
                                  className: logo
                                }, Utils$RescriptPpx.str("Loruki.")))), React.createElement("div", undefined, React.createElement("ul", {
                              className: navUl
                            }, React.createElement("a", {
                                  className: anchor,
                                  href: "loruki"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Home"))), React.createElement("a", {
                                  className: anchor,
                                  href: "loruki_features"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Features"))), React.createElement("a", {
                                  className: anchor,
                                  href: "loruki_docs"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Docs"))))))), React.createElement("section", {
                  className: featuresSection
                }, React.createElement("div", {
                      className: featuresFlex
                    }, React.createElement("div", undefined, React.createElement("h1", {
                              className: featuresHeading
                            }, Utils$RescriptPpx.str("Features")), React.createElement("p", {
                              className: featuresParagraph
                            }, Utils$RescriptPpx.str("Learn how to work with the Loruki platform"))), React.createElement("div", {
                          className: featuresImage
                        }, React.createElement("img", {
                              alt: "",
                              src: "/loruki/docs.png"
                            })))), React.createElement("section", {
                  className: docsSection
                }, React.createElement("div", {
                      className: docsFlex
                    }, React.createElement("div", {
                          className: essentialsBackground
                        }, React.createElement("div", undefined, React.createElement("h3", {
                                  className: docsHeading
                                }, Utils$RescriptPpx.str("Essentials")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Introduction")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("About Loruki")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Installation"))), React.createElement("div", undefined, React.createElement("h3", {
                                  className: docsHeading
                                }, Utils$RescriptPpx.str("Deployment")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Setting up a container")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Using CLI")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Managing Resources")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Upgrade & downgrade")))), React.createElement("div", {
                          className: essentialsBackground2
                        }, React.createElement("div", undefined, React.createElement("h1", {
                                  className: introductionHeading
                                }, Utils$RescriptPpx.str("Introduction")), React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio illo facere perferendis")), React.createElement("p", undefined, Utils$RescriptPpx.str(" laborum? Similique recusandae incidunt eos dolorum aliquam ipsam unde perspiciatis")), React.createElement("p", undefined, Utils$RescriptPpx.str(" laudantium totam quam laborum velit, at maxime minus?"))), React.createElement("div", {
                              className: infoPop
                            }, React.createElement("div", {
                                  className: infoIcon
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/information.svg"
                                    })), React.createElement("p", {
                                  className: popParagraph
                                }, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae, animi?"))), React.createElement("h1", {
                              className: introductionHeading2
                            }, Utils$RescriptPpx.str("Lorem, ipsum dolor.")), React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minima totam magni eius vitae")), React.createElement("p", undefined, Utils$RescriptPpx.str("velit id, atque veritatis! At, vero porro.")), React.createElement("button", {
                              className: cliInstall
                            }, Utils$RescriptPpx.str("Install CLI")), React.createElement("h1", {
                              className: introductionHeading2
                            }, Utils$RescriptPpx.str("Requirements")), React.createElement("p", undefined, Utils$RescriptPpx.str("Windows 10, Mac OSX, Linux")), React.createElement("p", undefined, Utils$RescriptPpx.str("Node.js v12 or higher")), React.createElement("h1", {
                              className: introductionHeading2
                            }, Utils$RescriptPpx.str("Install")), React.createElement("p", undefined, Utils$RescriptPpx.str("Mac (Homebrew)")), React.createElement("p", {
                              className: codePre
                            }, Utils$RescriptPpx.str("$ brew install loruki-cli")), React.createElement("p", undefined, Utils$RescriptPpx.str("NPM")), React.createElement("p", {
                              className: codePre
                            }, Utils$RescriptPpx.str("$ npm install loruki-cli")), React.createElement("p", undefined, Utils$RescriptPpx.str("Yarn")), React.createElement("p", {
                              className: codePre
                            }, Utils$RescriptPpx.str("$ yarn install loruki-cli"))))), React.createElement("footer", {
                  className: footerSection
                }, React.createElement("div", {
                      className: footerFlex
                    }, React.createElement("div", {
                          className: footerLeft
                        }, React.createElement("h1", {
                              className: footerHeading
                            }, Utils$RescriptPpx.str("Loruki")), React.createElement("p", undefined, Utils$RescriptPpx.str("Copyright 2020"))), React.createElement("div", undefined, React.createElement("a", {
                              href: "#"
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Home"))), React.createElement("a", {
                              href: ""
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Features"))), React.createElement("a", {
                              href: ""
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Docs")))), React.createElement("div", {
                          className: footerRight
                        }, React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/github.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/facebook.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/instagram.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/twitter.svg"
                            })))));
}

export {
  $$default ,
  $$default as default,
  
}
/* background Not a pure module */
