// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as Utils$RescriptPpx from "../utils/Utils.bs.js";
import * as Tailwind$RescriptPpx from "../styles/tailwind/Tailwind.bs.js";

var globalStyles = CssJs.style([
      CssJs.backgroundColor({
            NAME: "hex",
            VAL: "047aed"
          }),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 400
          })
    ]);

var header = CssJs.merge([
      Tailwind$RescriptPpx.mx80,
      Tailwind$RescriptPpx.p6,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textWhite(1)
    ]);

var navbar = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mb8
    ]);

var logo = CssJs.merge([
      Tailwind$RescriptPpx.text4Xl,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var navUl = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var anchor = CssJs.merge([Tailwind$RescriptPpx.mx4]);

var featuresSection = CssJs.merge([
      Tailwind$RescriptPpx.mx80,
      Tailwind$RescriptPpx.pb12
    ]);

var featuresFlex = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textWhite(1),
      Tailwind$RescriptPpx.justifyBetween
    ]);

var featuresImage = CssJs.merge([
      Tailwind$RescriptPpx.h48,
      Tailwind$RescriptPpx.w48
    ]);

var featuresHeading = CssJs.merge([
      Tailwind$RescriptPpx.text6Xl,
      Tailwind$RescriptPpx.mb6
    ]);

var featuresParagraph = CssJs.merge([Tailwind$RescriptPpx.textLg]);

var docsSection = CssJs.merge([
      Tailwind$RescriptPpx.bgWhite(1),
      Tailwind$RescriptPpx.pt12,
      Tailwind$RescriptPpx.pb2
    ]);

var docsFlex = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mx60,
      Tailwind$RescriptPpx.mb12
    ]);

var essentialsBackground = CssJs.merge([
      Tailwind$RescriptPpx.bgGray100(1),
      Tailwind$RescriptPpx.p8,
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.w76,
      Tailwind$RescriptPpx.rounded2Xl,
      Tailwind$RescriptPpx.shadow2Xl,
      Tailwind$RescriptPpx.mb92
    ]);

var docsHeading = CssJs.merge([
      Tailwind$RescriptPpx.textLg,
      Tailwind$RescriptPpx.my4
    ]);

var docsParagraph = CssJs.merge([
      Tailwind$RescriptPpx.borderB2,
      Tailwind$RescriptPpx.mb4
    ]);

var essentialsBackground2 = CssJs.merge([
      Tailwind$RescriptPpx.bgWhite(1),
      Tailwind$RescriptPpx.p8,
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.rounded2Xl,
      Tailwind$RescriptPpx.shadow2Xl
    ]);

var infoPop = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyCenter,
      Tailwind$RescriptPpx.bgGreen500(1),
      Tailwind$RescriptPpx.p2,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.roundedLg,
      Tailwind$RescriptPpx.mt6
    ]);

var infoIcon = CssJs.merge([
      Tailwind$RescriptPpx.w8,
      Tailwind$RescriptPpx.h8
    ]);

var popParagraph = CssJs.merge([Tailwind$RescriptPpx.pl4]);

var introductionHeading = CssJs.merge([
      Tailwind$RescriptPpx.text2Xl,
      Tailwind$RescriptPpx.mb2
    ]);

var introductionHeading2 = CssJs.merge([
      Tailwind$RescriptPpx.textLg,
      Tailwind$RescriptPpx.my4
    ]);

var cliInstall = CssJs.merge([
      Tailwind$RescriptPpx.bgBlue500(1),
      Tailwind$RescriptPpx.my4,
      Tailwind$RescriptPpx.p2,
      Tailwind$RescriptPpx.w36,
      Tailwind$RescriptPpx.roundedLg,
      Tailwind$RescriptPpx.textWhite(1)
    ]);

var codePre = CssJs.merge([
      Tailwind$RescriptPpx.bgGray800(1),
      Tailwind$RescriptPpx.textWhite(1),
      Tailwind$RescriptPpx.p2,
      Tailwind$RescriptPpx.my2,
      Tailwind$RescriptPpx.roundedLg
    ]);

var footerSection = CssJs.merge([
      Tailwind$RescriptPpx.bgIndigo900(1),
      Tailwind$RescriptPpx.textWhite(1)
    ]);

var footerFlex = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mx56,
      Tailwind$RescriptPpx.py18
    ]);

var footerLeft = CssJs.merge([
      Tailwind$RescriptPpx.block,
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var footerHeading = CssJs.merge([Tailwind$RescriptPpx.text3Xl]);

var footerRight = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.h14,
      Tailwind$RescriptPpx.w14,
      Tailwind$RescriptPpx.mr28
    ]);

var footerImage = CssJs.merge([Tailwind$RescriptPpx.mx4]);

function $$default(param) {
  return React.createElement("main", {
              className: globalStyles
            }, React.createElement("header", {
                  className: header
                }, React.createElement("nav", {
                      className: navbar
                    }, React.createElement("div", undefined, React.createElement("a", {
                              href: "loruki"
                            }, React.createElement("h1", {
                                  className: logo
                                }, Utils$RescriptPpx.str("Loruki.")))), React.createElement("div", undefined, React.createElement("ul", {
                              className: navUl
                            }, React.createElement("a", {
                                  className: anchor,
                                  href: "loruki"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Home"))), React.createElement("a", {
                                  className: anchor,
                                  href: "loruki_features"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Features"))), React.createElement("a", {
                                  className: anchor,
                                  href: "loruki_docs"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Docs"))))))), React.createElement("section", {
                  className: featuresSection
                }, React.createElement("div", {
                      className: featuresFlex
                    }, React.createElement("div", undefined, React.createElement("h1", {
                              className: featuresHeading
                            }, Utils$RescriptPpx.str("Features")), React.createElement("p", {
                              className: featuresParagraph
                            }, Utils$RescriptPpx.str("Learn how to work with the Loruki platform"))), React.createElement("div", {
                          className: featuresImage
                        }, React.createElement("img", {
                              alt: "",
                              src: "/loruki/docs.png"
                            })))), React.createElement("section", {
                  className: docsSection
                }, React.createElement("div", {
                      className: docsFlex
                    }, React.createElement("div", {
                          className: essentialsBackground
                        }, React.createElement("div", undefined, React.createElement("h3", {
                                  className: docsHeading
                                }, Utils$RescriptPpx.str("Essentials")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Introduction")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("About Loruki")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Installation"))), React.createElement("div", undefined, React.createElement("h3", {
                                  className: docsHeading
                                }, Utils$RescriptPpx.str("Deployment")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Setting up a container")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Using CLI")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Managing Resources")), React.createElement("p", {
                                  className: docsParagraph
                                }, Utils$RescriptPpx.str("Upgrade & downgrade")))), React.createElement("div", {
                          className: essentialsBackground2
                        }, React.createElement("div", undefined, React.createElement("h1", {
                                  className: introductionHeading
                                }, Utils$RescriptPpx.str("Introduction")), React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio illo facere perferendis")), React.createElement("p", undefined, Utils$RescriptPpx.str(" laborum? Similique recusandae incidunt eos dolorum aliquam ipsam unde perspiciatis")), React.createElement("p", undefined, Utils$RescriptPpx.str(" laudantium totam quam laborum velit, at maxime minus?"))), React.createElement("div", {
                              className: infoPop
                            }, React.createElement("div", {
                                  className: infoIcon
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/information.svg"
                                    })), React.createElement("p", {
                                  className: popParagraph
                                }, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae, animi?"))), React.createElement("h1", {
                              className: introductionHeading2
                            }, Utils$RescriptPpx.str("Lorem, ipsum dolor.")), React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minima totam magni eius vitae")), React.createElement("p", undefined, Utils$RescriptPpx.str("velit id, atque veritatis! At, vero porro.")), React.createElement("button", {
                              className: cliInstall
                            }, Utils$RescriptPpx.str("Install CLI")), React.createElement("h1", {
                              className: introductionHeading2
                            }, Utils$RescriptPpx.str("Requirements")), React.createElement("p", undefined, Utils$RescriptPpx.str("Windows 10, Mac OSX, Linux")), React.createElement("p", undefined, Utils$RescriptPpx.str("Node.js v12 or higher")), React.createElement("h1", {
                              className: introductionHeading2
                            }, Utils$RescriptPpx.str("Install")), React.createElement("p", undefined, Utils$RescriptPpx.str("Mac (Homebrew)")), React.createElement("p", {
                              className: codePre
                            }, Utils$RescriptPpx.str("$ brew install loruki-cli")), React.createElement("p", undefined, Utils$RescriptPpx.str("NPM")), React.createElement("p", {
                              className: codePre
                            }, Utils$RescriptPpx.str("$ npm install loruki-cli")), React.createElement("p", undefined, Utils$RescriptPpx.str("Yarn")), React.createElement("p", {
                              className: codePre
                            }, Utils$RescriptPpx.str("$ yarn install loruki-cli"))))), React.createElement("footer", {
                  className: footerSection
                }, React.createElement("div", {
                      className: footerFlex
                    }, React.createElement("div", {
                          className: footerLeft
                        }, React.createElement("h1", {
                              className: footerHeading
                            }, Utils$RescriptPpx.str("Loruki")), React.createElement("p", undefined, Utils$RescriptPpx.str("Copyright 2020"))), React.createElement("div", undefined, React.createElement("a", {
                              href: "#"
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Home"))), React.createElement("a", {
                              href: ""
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Features"))), React.createElement("a", {
                              href: ""
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Docs")))), React.createElement("div", {
                          className: footerRight
                        }, React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/github.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/facebook.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/instagram.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/twitter.svg"
                            })))));
}

export {
  $$default ,
  $$default as default,
  
}
/* globalStyles Not a pure module */
