// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as Utils$RescriptPpx from "../utils/Utils.bs.js";
import * as Tailwind$RescriptPpx from "../styles/tailwind/Tailwind.bs.js";

var globalStyles = CssJs.style([
      CssJs.backgroundColor({
            NAME: "hex",
            VAL: "047aed"
          }),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 400
          })
    ]);

var header = CssJs.merge([
      Tailwind$RescriptPpx.mx80,
      Tailwind$RescriptPpx.p6,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textWhite(1)
    ]);

var navbar = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mb8
    ]);

var logo = CssJs.merge([
      Tailwind$RescriptPpx.text4Xl,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var navUl = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var anchor = CssJs.merge([Tailwind$RescriptPpx.mx4]);

var featuresSection = CssJs.merge([
      Tailwind$RescriptPpx.mx80,
      Tailwind$RescriptPpx.pb12
    ]);

var featuresFlex = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textWhite(1),
      Tailwind$RescriptPpx.justifyBetween
    ]);

var featuresImage = CssJs.merge([
      Tailwind$RescriptPpx.h48,
      Tailwind$RescriptPpx.w48
    ]);

var featuresHeading = CssJs.merge([
      Tailwind$RescriptPpx.text7Xl,
      Tailwind$RescriptPpx.mb6
    ]);

var featuresParagraph = CssJs.merge([Tailwind$RescriptPpx.textLg]);

var platformSection = CssJs.merge([
      Tailwind$RescriptPpx.py12,
      Tailwind$RescriptPpx.bgGray100(1)
    ]);

var platformFlex = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.mx80,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.textBlack(1),
      Tailwind$RescriptPpx.justifyBetween
    ]);

var platformImage = CssJs.merge([
      Tailwind$RescriptPpx.h80,
      Tailwind$RescriptPpx.w80
    ]);

var platformHeading = CssJs.merge([
      Tailwind$RescriptPpx.text3Xl,
      Tailwind$RescriptPpx.mb6
    ]);

var platformParagraph = CssJs.merge([Tailwind$RescriptPpx.textSm]);

var row1 = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.p8,
      Tailwind$RescriptPpx.mb10,
      Tailwind$RescriptPpx.shadowXl,
      Tailwind$RescriptPpx.roundedXl,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.justifyCenter
    ]);

var row2 = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.mb2,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.justifyBetween
    ]);

var imageControl = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.w10,
      Tailwind$RescriptPpx.h10,
      Tailwind$RescriptPpx.mr4
    ]);

var gridSection = CssJs.merge([Tailwind$RescriptPpx.bgWhite(1)]);

var sectionBackground = CssJs.merge([
      Tailwind$RescriptPpx.mx52,
      Tailwind$RescriptPpx.py12
    ]);

var rowFlex = CssJs.merge([Tailwind$RescriptPpx.flex]);

var rowFlex2 = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.p8,
      Tailwind$RescriptPpx.pr20,
      Tailwind$RescriptPpx.h40,
      Tailwind$RescriptPpx.mb10,
      Tailwind$RescriptPpx.shadowXl,
      Tailwind$RescriptPpx.roundedXl,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.justifyCenter
    ]);

var rowFlex3 = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.p8,
      Tailwind$RescriptPpx.pl12,
      Tailwind$RescriptPpx.h40,
      Tailwind$RescriptPpx.mb10,
      Tailwind$RescriptPpx.shadowXl,
      Tailwind$RescriptPpx.roundedXl,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.justifyCenter
    ]);

var footerSection = CssJs.merge([
      Tailwind$RescriptPpx.bgIndigo900(1),
      Tailwind$RescriptPpx.textWhite(1)
    ]);

var footerFlex = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.justifyBetween,
      Tailwind$RescriptPpx.itemsCenter,
      Tailwind$RescriptPpx.mx56,
      Tailwind$RescriptPpx.py18
    ]);

var footerLeft = CssJs.merge([
      Tailwind$RescriptPpx.block,
      Tailwind$RescriptPpx.textLeft,
      Tailwind$RescriptPpx.itemsCenter
    ]);

var footerHeading = CssJs.merge([Tailwind$RescriptPpx.text3Xl]);

var footerRight = CssJs.merge([
      Tailwind$RescriptPpx.flex,
      Tailwind$RescriptPpx.h14,
      Tailwind$RescriptPpx.w14,
      Tailwind$RescriptPpx.mr28
    ]);

var footerImage = CssJs.merge([Tailwind$RescriptPpx.mx4]);

function $$default(param) {
  return React.createElement("main", {
              className: globalStyles
            }, React.createElement("header", {
                  className: header
                }, React.createElement("nav", {
                      className: navbar
                    }, React.createElement("div", undefined, React.createElement("a", {
                              href: "loruki"
                            }, React.createElement("h1", {
                                  className: logo
                                }, Utils$RescriptPpx.str("Loruki.")))), React.createElement("div", undefined, React.createElement("ul", {
                              className: navUl
                            }, React.createElement("a", {
                                  className: anchor,
                                  href: "loruki"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Home"))), React.createElement("a", {
                                  className: anchor,
                                  href: "loruki_features"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Features"))), React.createElement("a", {
                                  className: anchor,
                                  href: "loruki_docs"
                                }, React.createElement("li", undefined, Utils$RescriptPpx.str("Docs"))))))), React.createElement("section", {
                  className: featuresSection
                }, React.createElement("div", {
                      className: featuresFlex
                    }, React.createElement("div", undefined, React.createElement("h1", {
                              className: featuresHeading
                            }, Utils$RescriptPpx.str("Features")), React.createElement("p", {
                              className: featuresParagraph
                            }, Utils$RescriptPpx.str("Check out the features of Loruki that separate us from the")), React.createElement("p", {
                              className: featuresParagraph
                            }, Utils$RescriptPpx.str("competition"))), React.createElement("div", {
                          className: featuresImage
                        }, React.createElement("img", {
                              alt: "",
                              src: "/loruki/server.png"
                            })))), React.createElement("section", {
                  className: platformSection
                }, React.createElement("div", {
                      className: platformFlex
                    }, React.createElement("div", undefined, React.createElement("h1", {
                              className: platformHeading
                            }, Utils$RescriptPpx.str("The Loruki Platform")), React.createElement("p", {
                              className: platformParagraph
                            }, Utils$RescriptPpx.str("Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor cupiditate")), React.createElement("p", {
                              className: platformParagraph
                            }, Utils$RescriptPpx.str("dignissimos temporibus perspiciatis quae! Suscipit qui, consectetur ea ")), React.createElement("p", {
                              className: platformParagraph
                            }, Utils$RescriptPpx.str("consequatur, doloribus repellendus quasi, aut corporis nam alias culpa. ")), React.createElement("p", {
                              className: platformParagraph
                            }, Utils$RescriptPpx.str("Nostrum, inventore accusantium!"))), React.createElement("div", {
                          className: platformImage
                        }, React.createElement("img", {
                              alt: "",
                              src: "/loruki/server2.png"
                            })))), React.createElement("section", {
                  className: gridSection
                }, React.createElement("div", {
                      className: sectionBackground
                    }, React.createElement("div", {
                          className: row1
                        }, React.createElement("div", {
                              className: rowFlex
                            }, React.createElement("div", {
                                  className: imageControl
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/img.svg"
                                    })), React.createElement("div", undefined, React.createElement("p", undefined, Utils$RescriptPpx.str("\r\n                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas nemo saepe corrupti et dolorem voluptate at, nostrum rem voluptatem")), React.createElement("p", undefined, Utils$RescriptPpx.str("ab alias quia molestiae ea, libero nihil deserunt. Molestias, eum? Necessitatibus!"))))), React.createElement("div", {
                          className: row2
                        }, React.createElement("div", {
                              className: rowFlex2
                            }, React.createElement("div", {
                                  className: imageControl
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/img.svg"
                                    })), React.createElement("div", undefined, React.createElement("p", undefined, Utils$RescriptPpx.str("\r\n                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus recusandae")), React.createElement("p", undefined, Utils$RescriptPpx.str("perferendis culpa, reiciendis a itaque debitis qui vel dignissimos ipsum!")))), React.createElement("div", {
                              className: rowFlex3
                            }, React.createElement("div", {
                                  className: imageControl
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/img.svg"
                                    })), React.createElement("div", undefined, React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet")), React.createElement("p", undefined, Utils$RescriptPpx.str("consectetur, adipisicing elit.")), React.createElement("p", undefined, Utils$RescriptPpx.str("Debitis, magnam."))))), React.createElement("div", {
                          className: row2
                        }, React.createElement("div", {
                              className: rowFlex3
                            }, React.createElement("div", {
                                  className: imageControl
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/img.svg"
                                    })), React.createElement("div", undefined, React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet")), React.createElement("p", undefined, Utils$RescriptPpx.str("consectetur, adipisicing elit.")), React.createElement("p", undefined, Utils$RescriptPpx.str("Debitis, magnam.")))), React.createElement("div", {
                              className: rowFlex3
                            }, React.createElement("div", {
                                  className: imageControl
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/img.svg"
                                    })), React.createElement("div", undefined, React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet")), React.createElement("p", undefined, Utils$RescriptPpx.str("consectetur, adipisicing elit.")), React.createElement("p", undefined, Utils$RescriptPpx.str("Debitis, magnam.")))), React.createElement("div", {
                              className: rowFlex3
                            }, React.createElement("div", {
                                  className: imageControl
                                }, React.createElement("img", {
                                      alt: "",
                                      src: "/loruki/img.svg"
                                    })), React.createElement("div", undefined, React.createElement("p", undefined, Utils$RescriptPpx.str("Lorem ipsum dolor sit amet")), React.createElement("p", undefined, Utils$RescriptPpx.str("consectetur, adipisicing elit.")), React.createElement("p", undefined, Utils$RescriptPpx.str("Debitis, magnam."))))))), React.createElement("footer", {
                  className: footerSection
                }, React.createElement("div", {
                      className: footerFlex
                    }, React.createElement("div", {
                          className: footerLeft
                        }, React.createElement("h1", {
                              className: footerHeading
                            }, Utils$RescriptPpx.str("Loruki")), React.createElement("p", undefined, Utils$RescriptPpx.str("Copyright 2020"))), React.createElement("div", undefined, React.createElement("a", {
                              href: "#"
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Home"))), React.createElement("a", {
                              href: ""
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Features"))), React.createElement("a", {
                              href: ""
                            }, React.createElement("p", undefined, Utils$RescriptPpx.str("Docs")))), React.createElement("div", {
                          className: footerRight
                        }, React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/github.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/facebook.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/instagram.svg"
                            }), React.createElement("img", {
                              className: footerImage,
                              alt: "",
                              src: "/loruki/twitter.svg"
                            })))));
}

export {
  $$default ,
  $$default as default,
  
}
/* globalStyles Not a pure module */
